const names = ["Jacob Smith", "Mason Smith", "Ethan Smith", "Noah Williams", "William Thomas", "Liam Medina", "Michael Hicks", "Jayden Williams",
    "Alexander Brown", "Aiden Miller", "Daniel Medina", "Matthew Medina", "Elijah Sweeney", "Sophia Miller", "Emma Knight", "Isabella Chapman",
    "Olivia Knight", "Ava Chapman", "Emily Franklin", "Abigail Knight", "Mia Williams", "Madison Franklin", "Elizabeth Daniel", "Chloe Knight",
    "Ella Bowman", "Avery Hale", "Addison Dixon", "Aubrey Richards", "Jacob Watkins", "Mason Brown", "Ethan Mejia", "Noah Walters", "William Becker",
    "Liam Miller", "Michael Barnes", "Jayden Brown", "Alexander Keith", "Aiden Holt", "Daniel Miller", "Matthew Miller", "Elijah Mcdonald",
    "Sophia Thomas", "Emma Williams", "Isabella Wilcox", "Olivia Holt", "Ava Knight", "Emily Simmons", "Abigail Gilbert", "Mia Wade",
    "Madison Beck ", "Elizabeth Wells", "Chloe Smith", "Ella Newman", "Avery Beck", "Addison Willis", "Aubrey Willis", "Jacob Wu",
    "Mason Simmons", "Ethan Navarro", "Noah Simmons", "William Chandler", "Liam Knight", "Michael Chandler", "Jayden Williams",
    "Alexander Snyder", "Aiden Park", "Daniel Chandler", "Matthew Snyder", "Elijah Snyder", "Sophia Park", "Emma Brown", "Isabella Thomas",
    "Olivia Thomas", "Ava Brown", "Emily Bowman", "Abigail Mason",
    "Mia Mason", "Madison Thomas", "Elizabeth Brady", "Chloe Brown", "Ella Thomas", "Avery Brady", "Addison Gillespie", "Aubrey Knight"];